_wandb:
    value:
        cli_version: 0.24.0
        e:
            gv7zgn5zvao24xfzvgjaop48fal1jpnq:
                args:
                    - config/train_reverse.py
                email: nguyenso@dickinson.edu
                executable: /opt/anaconda3/bin/python
                git:
                    commit: dc8eef1f303b4ccdd7dc147bb68ff9663d7d8e37
                    remote: https://github.com/sonnguyen123526/comp560-sonnguyen.git
                host: Sons-MacBook-Pro-448.local
                os: macOS-26.3-arm64-arm-64bit
                program: /Users/sonnguyen/comp560-sonnguyen/transformer-algebra/../../comp560-nanoGPT/train.py
                python: CPython 3.11.7
                root: /Users/sonnguyen/comp560-sonnguyen/transformer-algebra
                startedAt: "2026-02-22T21:59:29.409423Z"
                writerId: gv7zgn5zvao24xfzvgjaop48fal1jpnq
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 13
                - 16
            "4": 3.11.7
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
always_save_checkpoint:
    value: false
backend:
    value: nccl
batch_size:
    value: 64
beta1:
    value: 0.9
beta2:
    value: 0.99
bias:
    value: false
block_size:
    value: 32
compile:
    value: false
dataset:
    value: reverse
decay_lr:
    value: true
device:
    value: cpu
dropout:
    value: 0.1
dtype:
    value: float16
eval_interval:
    value: 100
eval_iters:
    value: 20
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 1
init_from:
    value: scratch
learning_rate:
    value: 0.001
log_interval:
    value: 1
lr_decay_iters:
    value: 2000
max_iters:
    value: 2000
min_lr:
    value: 0.0001
n_embd:
    value: 128
n_head:
    value: 4
n_layer:
    value: 4
out_dir:
    value: out/reverse
wandb_log:
    value: true
wandb_project:
    value: transformer-algebra
wandb_run_name:
    value: reverse
warmup_iters:
    value: 100
weight_decay:
    value: 0.1
