_wandb:
    value:
        cli_version: 0.24.0
        e:
            5pis1wok6k2o1rdwfdqoicntbxx02r97:
                args:
                    - /Users/sonnguyen/comp560-sonnguyen/transformer-algebra/config/train_addition_ft.py
                email: nguyenso@dickinson.edu
                executable: /opt/anaconda3/bin/python
                git:
                    commit: 1cd04d2395ccc3aacb38718bd9ab7dac87e44d3b
                    remote: https://github.com/sonnguyen123526/comp560-sonnguyen.git
                host: Sons-MacBook-Pro-448.local
                os: macOS-26.3-arm64-arm-64bit
                program: /Users/sonnguyen/comp560-nanoGPT/train.py
                python: CPython 3.11.7
                root: /Users/sonnguyen/comp560-sonnguyen/transformer-algebra
                startedAt: "2026-02-25T04:36:32.732717Z"
                writerId: 5pis1wok6k2o1rdwfdqoicntbxx02r97
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
                - 105
            "3":
                - 13
                - 16
            "4": 3.11.7
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
always_save_checkpoint:
    value: false
backend:
    value: nccl
batch_size:
    value: 64
beta1:
    value: 0.9
beta2:
    value: 0.99
bias:
    value: false
block_size:
    value: 32
compile:
    value: false
dataset:
    value: addition
decay_lr:
    value: true
device:
    value: mps
dropout:
    value: 0
dtype:
    value: float16
eval_interval:
    value: 100
eval_iters:
    value: 20
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 1
init_from:
    value: resume
learning_rate:
    value: 0.003
log_interval:
    value: 1
lr_decay_iters:
    value: 5000
max_iters:
    value: 5000
min_lr:
    value: 0.0001
n_embd:
    value: 128
n_head:
    value: 4
n_layer:
    value: 4
out_dir:
    value: out/addition_ft
wandb_log:
    value: true
wandb_project:
    value: transformer-algebra
wandb_run_name:
    value: addition-ft
warmup_iters:
    value: 200
weight_decay:
    value: 0.1
