_wandb:
    value:
        cli_version: 0.24.0
        e:
            5m0z70xba9ot22kxy5gs6byjwgpcdemk:
                args:
                    - config/finetune_reverse.py
                email: nguyenso@dickinson.edu
                executable: /opt/anaconda3/bin/python
                git:
                    commit: 3ba6afeb89ab92ca59d1435ac1b16f64f466f735
                    remote: https://github.com/sonnguyen123526/comp560-sonnguyen.git
                host: Sons-MacBook-Pro-448.local
                os: macOS-26.3-arm64-arm-64bit
                program: /Users/sonnguyen/comp560-nanoGPT/train.py
                python: CPython 3.11.7
                root: /Users/sonnguyen/comp560-sonnguyen/transformer-algebra
                startedAt: "2026-02-24T20:45:23.594095Z"
                writerId: 5m0z70xba9ot22kxy5gs6byjwgpcdemk
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 13
                - 16
            "4": 3.11.7
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
always_save_checkpoint:
    value: false
backend:
    value: nccl
batch_size:
    value: 64
beta1:
    value: 0.9
beta2:
    value: 0.99
bias:
    value: false
block_size:
    value: 1024
compile:
    value: false
dataset:
    value: reverse_ft
decay_lr:
    value: true
device:
    value: mps
dropout:
    value: 0
dtype:
    value: float16
eval_interval:
    value: 100
eval_iters:
    value: 20
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 1
init_from:
    value: resume
learning_rate:
    value: 0.003
log_interval:
    value: 1
lr_decay_iters:
    value: 20000
max_iters:
    value: 20000
min_lr:
    value: 0.0001
n_embd:
    value: 768
n_head:
    value: 12
n_layer:
    value: 12
out_dir:
    value: out/reverse_ft
wandb_log:
    value: true
wandb_project:
    value: transformer-algebra
wandb_run_name:
    value: reverse_ft
warmup_iters:
    value: 200
weight_decay:
    value: 0.1
